In [3]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:
import pickle

file_path = '/content/drive/MyDrive/roberta_binary.pkl'

with open(file_path, 'rb') as f:
    rob_bin = pickle.load(f)

rob_bin

{'evaluation': [0.6931461691856384, 0.5058649182319641],
 'history': {'loss': [0.6941114664077759], 'accuracy': [0.49847665429115295]},
 'predicted_labels': array([0, 0, 0, ..., 0, 0, 0]),
 'actual_labels': array([1, 1, 1, ..., 0, 1, 0])}

In [19]:
from sklearn.metrics import confusion_matrix
import numpy as np

cm = confusion_matrix(rob_bin['actual_labels'], rob_bin['predicted_labels'])
cm

array([[17725,     0],
       [17314,     0]])

In [20]:
file_path = '/content/drive/MyDrive/roberta_tri.pkl'

with open(file_path, 'rb') as f:
    rob_tri = pickle.load(f)

rob_tri

{'evaluation': [1.0986310243606567, 0.3313101828098297],
 'history': {'loss': [1.099246859550476], 'accuracy': [0.33391523361206055]},
 'predicted_labels': array([2, 2, 2, ..., 2, 2, 2]),
 'actual_labels': array([1, 2, 1, ..., 0, 1, 1])}

In [21]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(rob_tri['actual_labels'], rob_tri['predicted_labels'])
cm

array([[    0,     0, 17495],
       [    0,     0, 17650],
       [    0,     0, 17413]])

In [22]:
file_path = '/content/drive/MyDrive/roberta_all.pkl'

with open(file_path, 'rb') as f:
    rob_all = pickle.load(f)

rob_all

{'evaluation': [12.88692855834961, 0.20063701272010803],
 'history': {'loss': [12.895709991455078], 'accuracy': [0.19983789324760437]},
 'predicted_labels': array([3, 3, 3, ..., 3, 3, 3]),
 'actual_labels': array([2, 0, 0, ..., 1, 3, 0])}

In [23]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(rob_all['actual_labels'], rob_all['predicted_labels'])
cm

array([[    0,     0,     0, 17490,     0],
       [    0,     0,     0, 17349,     0],
       [    0,     0,     0, 17666,     0],
       [    0,     0,     0, 17575,     0],
       [    0,     0,     0, 17516,     0]])