In [1]:
import pandas as pd
import json
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, cross_validate, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
from google.colab import drive

drive.mount('/content/drive')

file_path = '/content/drive/My Drive/cell_phones_accessories.json'

Mounted at /content/drive


In [4]:
with open(file_path, 'r') as file:
    data = [json.loads(line) for line in file]

df = pd.DataFrame(data)
df

rating                                              title  \
0          4.0                   No white background! It’s clear!   
1          5.0                Awesome!  Great price!  Works well!   
2          5.0                 Worked but took an hour to install   
3          4.0                                             Decent   
4          5.0                                           LOVE IT!   
...        ...                                                ...   
999995     3.0  First of all just an FYI for those wondering y...   
999996     5.0                              Very good protection.   
999997     5.0                                 Good charging cord   
999998     5.0                     Perfect for iPhone! Love this!   
999999     5.0                                 Super Easy Upgrade   

                                                     text  \
0       I bought this bc I thought it had the nice whi...   
1       Perfect. How pissed am I that I recently paid ...   
2       Overall very happy with the end result. If you...   
3       Lasted about 9 months then the lock button bro...   
4       LOVE THIS CASE! Works better than my expensive...   
...                                                   ...   
999995  First of all just an FYI for those wondering y...   
999996      Looks good works well. Nothing else I expect.   
999997  Nice and long and braided coating looks like i...   
999998  This is perfect for my iPhone. I've bought oth...   
999999  Bought this as an upgrade from a Galaxy J7 Cro...   

                                                   images        asin  \
0       [{'small_image_url': 'https://images-na.ssl-im...  B08L6L3X1S   
1                                                      []  B079BPGF6C   
2       [{'small_image_url': 'https://m.media-amazon.c...  B088DR7Z5B   
3       [{'small_image_url': 'https://images-na.ssl-im...  B07XRDHDNQ   
4                                                      []  B00A8ZDL9Y   
...                                                   ...         ...   
999995                                                 []  B00GGY8PAQ   
999996                                                 []  B07H11F2GG   
999997                                                 []  B01CY1CUB4   
999998                                                 []  B00GJ36AZG   
999999                                                 []  B07Y5R57FS   

       parent_asin                       user_id      timestamp  helpful_vote  \
0       B08L6L3X1S  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1612044451196             0   
1       B079BPGF6C  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1534443517349             2   
2       B0BBGGC8F2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1629235304798             3   
3       B07XRDHDNQ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1590470082910             0   
4       B00A8ZDL9Y  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1408994588000             0   
...            ...                           ...            ...           ...   
999995  B00GGY8PAQ  AH6G2UJ3CJ4PIO56IRAOF62GRWZQ  1419718065000             1   
999996  B07H11F2GG  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1566098076662             0   
999997  B01CY1CUB4  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1466052134000             0   
999998  B00GJ36AZG  AE2P2I3OV4K2N23GSAZADUCJ3RLQ  1435365140000             1   
999999  B07Y5R57FS  AFCZS6XOPWG7XKUKP5U2VHCOE4LQ  1603469648745             1   

        verified_purchase  
0                    True  
1                    True  
2                    True  
3                    True  
4                    True  
...                   ...  
999995               True  
999996               True  
999997               True  
999998               True  
999999              False  

[1000000 rows x 10 columns]

In [5]:
df

rating                                              title  \
0          4.0                   No white background! It’s clear!   
1          5.0                Awesome!  Great price!  Works well!   
2          5.0                 Worked but took an hour to install   
3          4.0                                             Decent   
4          5.0                                           LOVE IT!   
...        ...                                                ...   
999995     3.0  First of all just an FYI for those wondering y...   
999996     5.0                              Very good protection.   
999997     5.0                                 Good charging cord   
999998     5.0                     Perfect for iPhone! Love this!   
999999     5.0                                 Super Easy Upgrade   

                                                     text  \
0       I bought this bc I thought it had the nice whi...   
1       Perfect. How pissed am I that I recently paid ...   
2       Overall very happy with the end result. If you...   
3       Lasted about 9 months then the lock button bro...   
4       LOVE THIS CASE! Works better than my expensive...   
...                                                   ...   
999995  First of all just an FYI for those wondering y...   
999996      Looks good works well. Nothing else I expect.   
999997  Nice and long and braided coating looks like i...   
999998  This is perfect for my iPhone. I've bought oth...   
999999  Bought this as an upgrade from a Galaxy J7 Cro...   

                                                   images        asin  \
0       [{'small_image_url': 'https://images-na.ssl-im...  B08L6L3X1S   
1                                                      []  B079BPGF6C   
2       [{'small_image_url': 'https://m.media-amazon.c...  B088DR7Z5B   
3       [{'small_image_url': 'https://images-na.ssl-im...  B07XRDHDNQ   
4                                                      []  B00A8ZDL9Y   
...                                                   ...         ...   
999995                                                 []  B00GGY8PAQ   
999996                                                 []  B07H11F2GG   
999997                                                 []  B01CY1CUB4   
999998                                                 []  B00GJ36AZG   
999999                                                 []  B07Y5R57FS   

       parent_asin                       user_id      timestamp  helpful_vote  \
0       B08L6L3X1S  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1612044451196             0   
1       B079BPGF6C  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1534443517349             2   
2       B0BBGGC8F2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1629235304798             3   
3       B07XRDHDNQ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1590470082910             0   
4       B00A8ZDL9Y  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1408994588000             0   
...            ...                           ...            ...           ...   
999995  B00GGY8PAQ  AH6G2UJ3CJ4PIO56IRAOF62GRWZQ  1419718065000             1   
999996  B07H11F2GG  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1566098076662             0   
999997  B01CY1CUB4  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1466052134000             0   
999998  B00GJ36AZG  AE2P2I3OV4K2N23GSAZADUCJ3RLQ  1435365140000             1   
999999  B07Y5R57FS  AFCZS6XOPWG7XKUKP5U2VHCOE4LQ  1603469648745             1   

        verified_purchase  
0                    True  
1                    True  
2                    True  
3                    True  
4                    True  
...                   ...  
999995               True  
999996               True  
999997               True  
999998               True  
999999              False  

[1000000 rows x 10 columns]

In [6]:
df['verified_purchase'].value_counts()

verified_purchase
True     937676
False     62324
Name: count, dtype: int64

In [7]:
df = df.loc[df['verified_purchase'] != False]
df = df.reset_index(drop=True)
df

rating                                              title  \
0          4.0                   No white background! It’s clear!   
1          5.0                Awesome!  Great price!  Works well!   
2          5.0                 Worked but took an hour to install   
3          4.0                                             Decent   
4          5.0                                           LOVE IT!   
...        ...                                                ...   
937671     5.0                                         Five Stars   
937672     3.0  First of all just an FYI for those wondering y...   
937673     5.0                              Very good protection.   
937674     5.0                                 Good charging cord   
937675     5.0                     Perfect for iPhone! Love this!   

                                                     text  \
0       I bought this bc I thought it had the nice whi...   
1       Perfect. How pissed am I that I recently paid ...   
2       Overall very happy with the end result. If you...   
3       Lasted about 9 months then the lock button bro...   
4       LOVE THIS CASE! Works better than my expensive...   
...                                                   ...   
937671                                        Works well.   
937672  First of all just an FYI for those wondering y...   
937673      Looks good works well. Nothing else I expect.   
937674  Nice and long and braided coating looks like i...   
937675  This is perfect for my iPhone. I've bought oth...   

                                                   images        asin  \
0       [{'small_image_url': 'https://images-na.ssl-im...  B08L6L3X1S   
1                                                      []  B079BPGF6C   
2       [{'small_image_url': 'https://m.media-amazon.c...  B088DR7Z5B   
3       [{'small_image_url': 'https://images-na.ssl-im...  B07XRDHDNQ   
4                                                      []  B00A8ZDL9Y   
...                                                   ...         ...   
937671                                                 []  B00D3TAV5Y   
937672                                                 []  B00GGY8PAQ   
937673                                                 []  B07H11F2GG   
937674                                                 []  B01CY1CUB4   
937675                                                 []  B00GJ36AZG   

       parent_asin                       user_id      timestamp  helpful_vote  \
0       B08L6L3X1S  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1612044451196             0   
1       B079BPGF6C  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1534443517349             2   
2       B0BBGGC8F2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1629235304798             3   
3       B07XRDHDNQ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1590470082910             0   
4       B00A8ZDL9Y  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1408994588000             0   
...            ...                           ...            ...           ...   
937671  B00D3TAV5Y  AHQSE5R5DERCA6VNSYAOTN3YAWDQ  1425904962000             0   
937672  B00GGY8PAQ  AH6G2UJ3CJ4PIO56IRAOF62GRWZQ  1419718065000             1   
937673  B07H11F2GG  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1566098076662             0   
937674  B01CY1CUB4  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1466052134000             0   
937675  B00GJ36AZG  AE2P2I3OV4K2N23GSAZADUCJ3RLQ  1435365140000             1   

        verified_purchase  
0                    True  
1                    True  
2                    True  
3                    True  
4                    True  
...                   ...  
937671               True  
937672               True  
937673               True  
937674               True  
937675               True  

[937676 rows x 10 columns]

In [8]:
df['verified_purchase'].value_counts()

verified_purchase
True    937676
Name: count, dtype: int64

In [9]:
'''
TF-IDF
'''

'\nTF-IDF\n'

In [10]:
review_vec = CountVectorizer(min_df=3, tokenizer=nltk.word_tokenize)
review_counts = review_vec.fit_transform(df['text'])
review_counts

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


<937676x43717 sparse matrix of type '<class 'numpy.int64'>'
	with 27343441 stored elements in Compressed Sparse Row format>

In [11]:
tfidf_transformer = TfidfTransformer()
review_tfidf = tfidf_transformer.fit_transform(review_counts)
review_tfidf

<937676x43717 sparse matrix of type '<class 'numpy.float64'>'
	with 27343441 stored elements in Compressed Sparse Row format>

In [12]:
'''
80-20 train test split approach
'''

'\n80-20 train test split approach\n'

In [13]:
x_train, x_test, y_train, y_test = train_test_split(review_tfidf, df['rating'], test_size=0.2)

In [14]:
lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(x_train, y_train)
y_pred = lr_model.predict(x_test)

cf_matrix = confusion_matrix(y_test, y_pred)

print("---------------------------------------------------------------------------------------------------------------------")
print("80-20 split\n")
print("Accuracy:", accuracy_score(y_test, y_pred), "\n")
print(cf_matrix)
print("---------------------------------------------------------------------------------------------------------------------")

---------------------------------------------------------------------------------------------------------------------
80-20 split

Accuracy: 0.7348402440064841 

[[ 13835    935   1272    295   2666]
 [  4276   1099   2136    569   2388]
 [  2498    975   4080   2085   5269]
 [   820    242   2220   5059  15458]
 [  1261    200   1310   2852 113736]]
---------------------------------------------------------------------------------------------------------------------
