In [1]:
from google.colab import drive

drive.mount('/content/drive')

file_path = '/content/drive/My Drive/cell_phones_accessories.json'

Mounted at /content/drive


In [2]:
import os

if os.path.exists(file_path):
    print("File exists!")
else:
    print("File does not exist.")

File exists!


In [35]:
import json
import pandas as pd

with open(file_path, 'r') as file:
    data = [json.loads(line) for line in file]

df = pd.DataFrame(data)
df

rating                                              title  \
0          4.0                   No white background! It’s clear!   
1          5.0                Awesome!  Great price!  Works well!   
2          5.0                 Worked but took an hour to install   
3          4.0                                             Decent   
4          5.0                                           LOVE IT!   
...        ...                                                ...   
999995     3.0  First of all just an FYI for those wondering y...   
999996     5.0                              Very good protection.   
999997     5.0                                 Good charging cord   
999998     5.0                     Perfect for iPhone! Love this!   
999999     5.0                                 Super Easy Upgrade   

                                                     text  \
0       I bought this bc I thought it had the nice whi...   
1       Perfect. How pissed am I that I recently paid ...   
2       Overall very happy with the end result. If you...   
3       Lasted about 9 months then the lock button bro...   
4       LOVE THIS CASE! Works better than my expensive...   
...                                                   ...   
999995  First of all just an FYI for those wondering y...   
999996      Looks good works well. Nothing else I expect.   
999997  Nice and long and braided coating looks like i...   
999998  This is perfect for my iPhone. I've bought oth...   
999999  Bought this as an upgrade from a Galaxy J7 Cro...   

                                                   images        asin  \
0       [{'small_image_url': 'https://images-na.ssl-im...  B08L6L3X1S   
1                                                      []  B079BPGF6C   
2       [{'small_image_url': 'https://m.media-amazon.c...  B088DR7Z5B   
3       [{'small_image_url': 'https://images-na.ssl-im...  B07XRDHDNQ   
4                                                      []  B00A8ZDL9Y   
...                                                   ...         ...   
999995                                                 []  B00GGY8PAQ   
999996                                                 []  B07H11F2GG   
999997                                                 []  B01CY1CUB4   
999998                                                 []  B00GJ36AZG   
999999                                                 []  B07Y5R57FS   

       parent_asin                       user_id      timestamp  helpful_vote  \
0       B08L6L3X1S  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1612044451196             0   
1       B079BPGF6C  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1534443517349             2   
2       B0BBGGC8F2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1629235304798             3   
3       B07XRDHDNQ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1590470082910             0   
4       B00A8ZDL9Y  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1408994588000             0   
...            ...                           ...            ...           ...   
999995  B00GGY8PAQ  AH6G2UJ3CJ4PIO56IRAOF62GRWZQ  1419718065000             1   
999996  B07H11F2GG  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1566098076662             0   
999997  B01CY1CUB4  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1466052134000             0   
999998  B00GJ36AZG  AE2P2I3OV4K2N23GSAZADUCJ3RLQ  1435365140000             1   
999999  B07Y5R57FS  AFCZS6XOPWG7XKUKP5U2VHCOE4LQ  1603469648745             1   

        verified_purchase  
0                    True  
1                    True  
2                    True  
3                    True  
4                    True  
...                   ...  
999995               True  
999996               True  
999997               True  
999998               True  
999999              False  

[1000000 rows x 10 columns]

In [36]:
df = df.loc[df['verified_purchase'] != False]
df = df.reset_index(drop=True)
df

rating                                              title  \
0          4.0                   No white background! It’s clear!   
1          5.0                Awesome!  Great price!  Works well!   
2          5.0                 Worked but took an hour to install   
3          4.0                                             Decent   
4          5.0                                           LOVE IT!   
...        ...                                                ...   
937671     5.0                                         Five Stars   
937672     3.0  First of all just an FYI for those wondering y...   
937673     5.0                              Very good protection.   
937674     5.0                                 Good charging cord   
937675     5.0                     Perfect for iPhone! Love this!   

                                                     text  \
0       I bought this bc I thought it had the nice whi...   
1       Perfect. How pissed am I that I recently paid ...   
2       Overall very happy with the end result. If you...   
3       Lasted about 9 months then the lock button bro...   
4       LOVE THIS CASE! Works better than my expensive...   
...                                                   ...   
937671                                        Works well.   
937672  First of all just an FYI for those wondering y...   
937673      Looks good works well. Nothing else I expect.   
937674  Nice and long and braided coating looks like i...   
937675  This is perfect for my iPhone. I've bought oth...   

                                                   images        asin  \
0       [{'small_image_url': 'https://images-na.ssl-im...  B08L6L3X1S   
1                                                      []  B079BPGF6C   
2       [{'small_image_url': 'https://m.media-amazon.c...  B088DR7Z5B   
3       [{'small_image_url': 'https://images-na.ssl-im...  B07XRDHDNQ   
4                                                      []  B00A8ZDL9Y   
...                                                   ...         ...   
937671                                                 []  B00D3TAV5Y   
937672                                                 []  B00GGY8PAQ   
937673                                                 []  B07H11F2GG   
937674                                                 []  B01CY1CUB4   
937675                                                 []  B00GJ36AZG   

       parent_asin                       user_id      timestamp  helpful_vote  \
0       B08L6L3X1S  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1612044451196             0   
1       B079BPGF6C  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1534443517349             2   
2       B0BBGGC8F2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1629235304798             3   
3       B07XRDHDNQ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1590470082910             0   
4       B00A8ZDL9Y  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1408994588000             0   
...            ...                           ...            ...           ...   
937671  B00D3TAV5Y  AHQSE5R5DERCA6VNSYAOTN3YAWDQ  1425904962000             0   
937672  B00GGY8PAQ  AH6G2UJ3CJ4PIO56IRAOF62GRWZQ  1419718065000             1   
937673  B07H11F2GG  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1566098076662             0   
937674  B01CY1CUB4  AHQGXL5L3VG6EBZFAQP4R6IPOTGQ  1466052134000             0   
937675  B00GJ36AZG  AE2P2I3OV4K2N23GSAZADUCJ3RLQ  1435365140000             1   

        verified_purchase  
0                    True  
1                    True  
2                    True  
3                    True  
4                    True  
...                   ...  
937671               True  
937672               True  
937673               True  
937674               True  
937675               True  

[937676 rows x 10 columns]

In [5]:
!pip install tensorflow-text

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 71.9 MB/s eta 0:00:00


In [37]:
df = df[:10000]
df

rating                                title  \
0        4.0     No white background! It’s clear!   
1        5.0  Awesome!  Great price!  Works well!   
2        5.0   Worked but took an hour to install   
3        4.0                               Decent   
4        5.0                             LOVE IT!   
...      ...                                  ...   
9995     5.0                           Nice band.   
9996     5.0          Works great for galaxy s10+   
9997     5.0                       Great charger.   
9998     5.0                            Very nice   
9999     5.0                         Good quality   

                                                   text  \
0     I bought this bc I thought it had the nice whi...   
1     Perfect. How pissed am I that I recently paid ...   
2     Overall very happy with the end result. If you...   
3     Lasted about 9 months then the lock button bro...   
4     LOVE THIS CASE! Works better than my expensive...   
...                                                 ...   
9995  Very nice band. Pretty much identical quality ...   
9996  Great product. Charges my samsung galaxy s10+ ...   
9997  I have a samsung s7 edge and was having issues...   
9998  Very easy to put on. Comes with microfiber clo...   
9999  Nice quality. Work well for my Samsung phone a...   

                                                 images        asin  \
0     [{'small_image_url': 'https://images-na.ssl-im...  B08L6L3X1S   
1                                                    []  B079BPGF6C   
2     [{'small_image_url': 'https://m.media-amazon.c...  B088DR7Z5B   
3     [{'small_image_url': 'https://images-na.ssl-im...  B07XRDHDNQ   
4                                                    []  B00A8ZDL9Y   
...                                                 ...         ...   
9995                                                 []  B07RKKS77P   
9996                                                 []  B07CJ2BVS1   
9997                                                 []  B06XXZK99F   
9998                                                 []  B01GIJS828   
9999                                                 []  B01ER9U3NS   

     parent_asin                       user_id      timestamp  helpful_vote  \
0     B08L6L3X1S  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1612044451196             0   
1     B079BPGF6C  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1534443517349             2   
2     B0BBGGC8F2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1629235304798             3   
3     B07XRDHDNQ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1590470082910             0   
4     B00A8ZDL9Y  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1408994588000             0   
...          ...                           ...            ...           ...   
9995  B07T6SXS57  AEQWBQRXKLE4LUTXZ7MOY54HVTCQ  1575040719927             0   
9996  B07PWDF1DM  AEQWBQRXKLE4LUTXZ7MOY54HVTCQ  1571082686565             0   
9997  B084VNCBNZ  AEQWBQRXKLE4LUTXZ7MOY54HVTCQ  1546852250149             0   
9998  B01GIJS828  AEQWBQRXKLE4LUTXZ7MOY54HVTCQ  1529014973393             0   
9999  B01JCKQHYG  AEQWBQRXKLE4LUTXZ7MOY54HVTCQ  1519467857701             0   

      verified_purchase  
0                  True  
1                  True  
2                  True  
3                  True  
4                  True  
...                 ...  
9995               True  
9996               True  
9997               True  
9998               True  
9999               True  

[10000 rows x 10 columns]

In [38]:
import tensorflow as tf
from transformers import TFBertTokenizer, TFBertForSequenceClassification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

reviews = df['text'].tolist()
ratings = df['rating'].tolist()

In [39]:
label_encoder = LabelEncoder()
ratings_encoded = label_encoder.fit_transform(ratings)

ratings_encoded

array([3, 4, 4, ..., 4, 4, 4])

In [40]:
X_train, X_test, y_train, y_test = train_test_split(reviews, ratings_encoded, test_size=0.2)

In [41]:
tokenizer = TFBertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(label_encoder.classes_))

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [42]:
train_encodings = tokenizer(X_train, truncation=True, padding='max_length', max_length=128)
test_encodings = tokenizer(X_test, truncation=True, padding='max_length', max_length=128)

In [43]:
train_encodings

{'input_ids': <tf.Tensor: shape=(8000, 128), dtype=int64, numpy=
 array([[ 101, 1045, 2293, ...,    0,    0,    0],
        [ 101, 4149, 2023, ...,    0,    0,    0],
        [ 101, 2200, 2204, ...,    0,    0,    0],
        ...,
        [ 101, 2204, 3976, ...,    0,    0,    0],
        [ 101, 1045, 2001, ..., 2424, 2041,  102],
        [ 101, 4299, 2027, ...,    0,    0,    0]])>,
 'attention_mask': <tf.Tensor: shape=(8000, 128), dtype=int64, numpy=
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 0, 0, 0]])>,
 'token_type_ids': <tf.Tensor: shape=(8000, 128), dtype=int64, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])>}

In [44]:
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    y_train
)).shuffle(1000).batch(16)

train_dataset

<_BatchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 128), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 128), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(None, 128), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [45]:
test_dataset = tf.data.Dataset.from_tensor_slices((
    dict(test_encodings),
    y_test
)).batch(16)

test_dataset

<_BatchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 128), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 128), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(None, 128), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [46]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [47]:
model.summary()

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
 dropout_37 (Dropout)        multiple                  0 (unused)
                                                                 
 classifier (Dense)          multiple                  3845      
                                                                 
Total params: 109486085 (417.66 MB)
Trainable params: 109486085 (417.66 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [49]:
model.fit(train_dataset, epochs=3)

Epoch 1/3
500/500 [==============================] - 233s 400ms/step - loss: 1.6953 - accuracy: 0.1055
Epoch 2/3
500/500 [==============================] - 199s 399ms/step - loss: 1.6147 - accuracy: 0.1014
Epoch 3/3
500/500 [==============================] - 200s 399ms/step - loss: 1.6089 - accuracy: 0.1010


In [50]:
model.evaluate(test_dataset)

125/125 [==============================] - 21s 146ms/step - loss: 1.6094 - accuracy: 0.0895


[1.6094363927841187, 0.08950000256299973]

In [34]:
from keras import backend

backend.clear_session()